language: go
go:
  - master
env:
  global:
    - DNSPOD_DEBUG=true
script:
  - if [ -n "$DNSPOD_LOGIN_TOKEN" ]; then env TF_ACC=true go test -v ./...; fi
  - if [ -z "$DNSPOD_LOGIN_TOKEN" ]; then go test -v ./...; fi
before_deploy:
  - 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -a -installsuffix cgo -o pkg/terraform-provider-dnspod_linux_amd64 .'
  - 'CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -a -installsuffix cgo -o pkg/terraform-provider-dnspod_darwin_amd64 .'
deploy:
  provider: releases
  api_key:
    secure: Nm0u4lqDWHRtsT+hVPhpKNLCkIStLXNUN46/szfQRFTML1eMvG/WKWh7llA4sP9LdjQMWi7ekBNyy6qxaVmwV/uCqQk1pVZ8hKGYYL3QpllOaCzYTqTGl99sIUZpCAX9zt1sfg6FOkMnAjt11t5th/0E8GgJssgue1N+hPS/LZwVvbE0D8IlnNd6M8xuKEVDozWDRDl2CmSf14cvkdAAWwkCudFQRZIsvDGspacrBZVTAdXkJ7LkLzUZZq23Spj4hav9kw5A2DCxeu7tXm6FJwGHEeMruxsSQzp+w76D8yAnVstx8XkV6kX7irvnK/rUmVrOfrLOmsYJ/uCxzHdV2LO843yhICa5yQkfW6M4s3NDFZ6tUMoiFUabf+U+WtpyI160XZeRlIWgglcom5bMMZBMFvtThkx+sAJdyquIYlw8GR97NLC5lZNsbBv83sr2RhjX6h999bFxEdzckNHXyn7yHF+P9HqexYugyYlsph8dZFOh/GKZAvnvj39Sfbdn6xedCRn4tlqPlAgXlN2HlC4btXaytewWS6OMt82lL3I2BhYFWxCDEr0E6Vjybsrns99J0pfPWHZs75IKGXpkkMhFjxrU2q6Kwb4ZkzNm3t+NK7ZMJCx1wERMhNrDiEk3sh/DNLrdaN9VBguZp2qdfBUWtGnXgy4geBKlin6FusI=
  file:
    - "pkg/terraform-provider-dnspod_linux_amd64"
    - "pkg/terraform-provider-dnspod_darwin_amd64"
  on:
    tags: true
    repo: 3pjgames/terraform-provider-dnspod
  skip_cleanup: true
